### ISSUE TITLE
Mode Changes Erratic

### ISSUE THREAD

**Issue by paullsoucy** [stelpro/Ki-ZigBee-Thermostat#1]
When I change from Comfort to Eco to Off,  it is very slow and erratic.  Often I have to leave the device then return to get the proper status.  Also when I go from Eco to Off, the stat changes mode to off then to Comfort.  Once this happens, I often find the stat no longer responds to mode changes.

**Comment by stelpro** [comment]
Hi Paul,

Could you tell me what is the source of the mode change? From the device or from the SmartThings app?

**Comment by paullsoucy** [comment]
I am only using the stelpro device driver  mode tile and not an automation. BTW I don't use this thermostat often in the summer but when I replaced my SmartThings to the 2.0 hub and the reduced latency improved the performance. I will test it more completely later. I think the issue was due to a weak signal and latency. 

Paul

**Comment by paullsoucy** [comment]
Please close this issue.  It was resolved once I replaced my SmartThings to the 2.0 hub and the reduced latency.
