### ISSUE TITLE
Always "heating to" 

### ISSUE THREAD

**Issue by kevnord** [stelpro/Ki-ZigBee-Thermostat#2]
Using this DeviceHandler (thank you for creating it!) on my new Stelpro Orleans Convector Wall heater.

Even when setpoint is lower than room temp, Smartthings App shows as "heating". See screenshot.

![media-20170710](https://user-images.githubusercontent.com/1149922/28030671-968f29ea-6559-11e7-8bab-30036f2142fe.png)

Also, the "configure" tile doesn't do anything

**Comment by stelpro** [comment]
Hi Kevin,

When you are seeing this behavior, is the Orlean Convector really heating?

**Comment by stelpro** [comment]
Is your Orlean Convector running at the specified setpoint?
If not, it could be a connection issue between the device and the SmartThings hub.

**Comment by kevnord** [comment]
I don't believe it's running but I'm unable to easily check now as I installed the heater in a vacation rental property of ours. I'll see if I can reset the hub or if there are other options which I can do remotely.

**Comment by kevnord** [comment]
Thanks for the quick response, btw.

**Comment by paullsoucy** [comment]
I have a related issue in that the set temperature between the up and down arrow is blank (I didn't know there should be one until I saw this post).  I have to go to the "Recently" screen to see the set temp.  If i increase the temp enough to start the heater, the "heating to xx" appears but otherwise I cannot see the set temperature. If I get the heating to message and the color turns to orange, it will not return to green once I bring the temp down below the set temp. It continues to show "heating to 74" when the room temp is 79. The heater is Not on in this condition though it says "heating to xx"  BTW I also have the Z-Wave version of this thermostat.  The "Heating to" and color works fine but it also does not show the set point temp between the up and down arrows. It would be very convenient to have a slide bar to raise and lower the temp rather than hitting an up or down arrow to make the change.  I am not typically making a minor adjustment but rather a much larger change when I arrive or depart my cottage.

**Comment by stelpro** [comment]
Hi Paul, since you refer to the Z-Wave version, please post on the appropriate thread.
Despite being very similar, both device handlers are different and must not be mixed

**Comment by paullsoucy** [comment]
I will. 
Thank you

Paul

**Comment by kevnord** [comment]
Greetings. I reset/restarted my Smartthings hub and tried everything I could remotely, but the ST App still continues to say "Heating to x" (and the tile is orange) even when the unit is not actually heating because the room temp is greater than the set point. Is there anything else I can try/check (remotely)?

**Comment by stelpro** [comment]
Please try to power cycle your convector.

**Comment by kevnord** [comment]
Is there a way to do this remotely? If not, I will have to find someone near the vacation rental property (where the convector is installed) to flip the breaker box off and on.

**Comment by stelpro** [comment]
No, you cannot power cycle the unit remotely (and since you have connection issue, it's most likely that it wouldn't work anyway).

You need to go to the physical location.

**Comment by paullsoucy** [comment]
I am having the same issue as kevnord  but  unlike him, my cottage is equipped with a remote power cycler; my wife :)
Once she cycled the breaker on and off the"Heating to xx" cleared and the status tile reverted to green with "Comfort".

**Comment by kevnord** [comment]
Hey Paul, do you have to recycle it often or did one recycle fix it?

**Comment by paullsoucy** [comment]
Kevin, My wife shutoff the breaker, gave it a 10 count and turned it back on.  I have 2 hubs in 2 homes so to be safe I toggled to my other location and back before I checked the status. I did not reboot or do anything else.

**Comment by paullsoucy** [comment]
The cycling of the power on & off cleared the "heating to xx" issue but did not resolve the fact that I still do not have a set temp showing between the up and down arrows as Kevin's screen shot shows.

**Comment by kevnord** [comment]
Thanks for the info, Paul! I'll give that a shot. Appreciate the help!
Do you have any other interesting devices setup in your homes that you recommend?
I updated all of the (baseboard/convector) thermostats to Stelpro Kis and added door and water (crawlspace) sensors. I want to add some zwave light switches but that's about it.

**Comment by paullsoucy** [comment]
Kevin,
I have a Schlage door lock, garage door opener, numerous water/leak & temp/humidity sensors, a water main valve and a 220V contractor to shutoff my water heater and z-wave lights, outlets dimmers & paddle fan switches.
With one home in RI and the other in FL, I can pre-heat or pre-cool or shut down either home before I arrive or upon departure.  For example my "Shutdown" automation  locks the front door, closes the garage, turns off various lights and water heater, shuts the water main, and sets the temp to either standby heating in the winter or standby cooling/dehumidification of my FL home when we are away. 
I have also integrated each home with Alexa so certain features can be controlled verbally; Lights on/off, or dimmed, change the temperature, lock the front door, etc.  Until I added Alexa, my wife didn't use Smartthings other than what I automated.  Now she uses it more.
 Paul

**Comment by kevnord** [comment]
Nicely done! I thought about getting a 220V contractor to shut off my water heater... may need to make that a priority. Our cottage is on San Juan Island here in WA State. It's completely booked from June'ish through Sept and hardly rented the rest of the year. We could likely save some $ by shutting down the water heater during the off-season. 

I just ordered an Alexa today as they're 1/2 price on Amazon right now, if you're a Prime member. I work only a few blocks from Amazon HQ... so becoming a Prime member is unavoidable. :-)

**Comment by kevnord** [comment]
Well hmmm....
I was able to find someone to off/on the heaters braker switch.
Initially, things looked great! Setpoint at 60, Temp at 70, tile green, no "heating to..." perfect!
I set the setpoint to 75, tile turned orange, "heating to 75" was displayed... again, perfect!
Then, I dropped the setpoint back to 60... tile renamed orange and "heating to 60" was displayed even though it's clearly below 70.
Not sure to go from here other than taking a look at the device handler code and/or forking off my own version.

**Comment by paullsoucy** [comment]
Kevin,
This is what I found as well.  Cycling the breaker clears the "heating to" but the issue returns after the condition for heating happens again. Paul

**Comment by kevnord** [comment]
I'll see if I can make sense of the 600+ lines of code in the handler and come up with a fix. I'm not a javascript expert but am a software engineer by day (allrecipes.com) so there's a chance I can get it to work.

**Comment by stelpro** [comment]
I'm currently working on it.
SmartThings made a lot of changes in their platform since I produced the device handler.
Some commands are broken

**Comment by kevnord** [comment]
Splendid! Thanks "stelpro" for you help... it's greatly appreciated! Let me
know if there's anything else I can do to help.

**Comment by stelpro** [comment]
I have created a branch with a test version.

Give it a try and let me know the outcome.
I'm out for the day.

https://github.com/stelpro/Ki-ZigBee-Thermostat/blob/BugFix-Always-%22heating-to%22/Stelpro-SmartThing%20Device%20Handler(MultiAttribute).txt

**Comment by kevnord** [comment]
The test version seems to fix the issue! The up down setpoint buttons seems slow to respond but I've noticed that before and it seems to improve somehow 

Thanks

**Comment by stelpro** [comment]
Branch merged with trunk.
Issue closed
