### ISSUE TITLE
Unable to change thermostat settings. SmartThings is only able to read them

### ISSUE THREAD

**Issue by HappyMonkeyPaul** [stelpro/Ki-ZigBee-Thermostat#6]
I can't change my thermostat's set point with SmartThings either manually or via a SmartApp. Using the device handler the thermostat pairs with my hub fine and all the state information like the current temperature and setpoint are available in the app. But when I try and change any value none of the modifications are ever reflected on the thermostat or the app. Their just lost in the aether somewhere.

Here are the app/os versions I'm using:

- Android: 8.0
- SmartThings: 2.6.1
- ZigBee Device Handler: 2017-07-21

Attaching some screenshots of the events attempting to change the temperature but never actually succeeding. It always attempts to go from 60 -> 61 never actually making it even though the commands return success.

![screen shot 2017-10-02 at 11 57 49 am](https://user-images.githubusercontent.com/786216/31094313-92ce92d0-a769-11e7-8b13-ee95952efbd8.jpg)
![screen shot 2017-10-02 at 11 59 08 am](https://user-images.githubusercontent.com/786216/31094312-92cdfb2c-a769-11e7-81b7-d006dbdafccf.jpg)

**Comment by stelpro** [comment]
Please try the following:
- Press the "Configure" button on the Device Handler

If it does not work, delete the device and pair it again then press the Configure button.

Android 8.0 is kind of new and SmartThings made some changes of their own, so there are lots of changes recently to account for.

**Comment by HappyMonkeyPaul** [comment]
Configure didn't do anything. I deleted and repaired the thermostat and configure is still broken. However after the second pairing I'm able to adjust the setpoint up/down manually. So that's an improvement.

**Comment by stelpro** [comment]
Please retry with the latest device handler code

**Comment by MeltingMosaic** [comment]
I hit a similar issue. I took a look in the debug console, and it seems that the device can be stuck with `thermostatMode` in the `"off"` setting with no way out. I got out by directly running `heat()`, but that's probably not going to work well for non-devs ;). I think I got into it by setting the device set point to 0F, which isn't checked by the handler code. I can mess with it and see about a fix if you guys accept PRs.

**Comment by stelpro** [comment]
Feel free to try your own fix.
You may submit it if you find out it fixes your issue.
Stelpro will then review it and decide of its implementation or not.

**Comment by stelpro** [comment]
Hi all,

This is to inform you that the Stelpro Ki Zigbee thermostat is now officially supported by SmartThings.

This means you no longer need to use the device handler code found in github.
**This also means that this device handler code will not get updated.**

The thermostat also works with the new SmartThings app.

There may be still some issues due to the multiple platform changes.
Feel free to report them to SmartThings.

Enjoy!

**Comment by kevnord** [comment]
This is great! Can't wait to try it out! Thank you so much.
