### ISSUE TITLE
Will this work with new Samsung Smartthings Android app?

### ISSUE THREAD

**Issue by kevnord** [stelpro/Ki-ZigBee-Thermostat#8]
Greetings!
I've been using this handler with my ST 2 hub and Android app. Samsung is phasing out the Smartthings app (now called Smartthings Classic) and moving everyone to a new Smartthings app (previous called Samsung Connect). 

Has anyone tried this handler with the new app?

**Comment by stelpro** [comment]
Hi,

It does not work with the new app yet.

**Comment by bfajg** [comment]
Hi,

Do you have an idea when this will work with the new App? Not that it is a major issue but some devices are now much better handled in the new App and it will be better to have everything in the same spot.

I use the IOS version but I think it is the same problem as with Android.

Regards,

Benjamin

**Comment by stelpro** [comment]
Currently, we are still targeting this fall.
So, in few weeks.
The Ki Z-Wave should already be working with the new app.
SmartThings is actively working on the zigbee version as we speak.

**Comment by bfajg** [comment]
Hello,

That's a good news, I'll be patient.

While I have you, one quick question. With the Stelpro controler the
exterior temperature was indicated on the Maestro thermostats. I have found
the handler to push tthe info on both the thermostats and the convestors
and the logs seems to confirm it works. No indication on the Maestros
though.

Is it really working well? Is there a way to have the temperature indicated
again without the Stelpro controler?

For the records, I tried everything with it but my two floors house did not
permit the Zigbee network to reach all the convectors downstairs. I changed
for a Samsung hub with a stronger signal and now everything is online. It
is a shame because the Stelpro app is very good, I hope you will find a way
to make your controler signal stronger for your futur clients.

Regards,

Benjamin

**Comment by stelpro** [comment]
Hi Benjamin,

Regarding the zigbee signal strength, some installations may require a zigbee repeater or a range extender.
Especially when you have devices on different floors.
Check out these links:
https://www.digikey.ca/products/en?keywords=CGW-Z-0010-01-00-ND
https://www.amazon.ca/Centralite-ZigBee-Plug-Lamp-Module/dp/B01CRJZVRI/ref=sr_1_1?s=electronics&ie=UTF8&qid=1518537032&sr=1-1&keywords=centralite

Regarding the outdoor temperature, it is working well when you use the Maestro Controler device.

When you switch to use a SmartThings hub as central point, the current SmartThings platform has a hard time to push new temperature every hour.
So after 4 hours without receiving a new outdoor temperature value, the temperature is declared invalid by the thermostat and it disappears.
This is something that should be fixed when the new device handler will be officially released by SmartThings.

**Comment by stelpro** [comment]
If you plan to buy a range extender, I must say that the Cortet range extender is incredibly efficient.

**Comment by bfajg** [comment]
I was looking into buying a range extender. After having done the maths it
was a lot cheaper to buy a smartthings hub (100$) and change my Maestro
controler for a maestro slave thermostat. Also the hub opens a lot of other
opportunities to add other smartthings in my house.

Overall the Orlean convector, the maestro thermostats and the uniwatt
convectors I installed are all great. Always good to buy Québécois too.

**Comment by Danzig69** [comment]
En français, produit Québecois, j'ai 3 Ki STZB402+ avec la fonction OFF que j'utilise, j'utilise aussi Eco.
Pour moi le Handler de Stelpro fonctionne partiellement dans la nouvelle appli 2018
https://github.com/stelpro/Ki-ZigBee-Thermostat/blob/master/devicetypes/stelpro/stelpro-ki-zigbee-thermostat.src/stelpro-ki-zigbee-thermostat.groovy
Je n'ai pas le mode Eco de disponible. J'ai chaleur et Désactivé. Tout le reste fonctionne.

Si j'utilise le Handler intégré de SmartThings Stelpro Ki Thermostat
J'ai Eco et Chaleur mais pas Désactivé. Et il Ajoute une ligne "Alerte de température"

Dans les 2 Handler, je peux changer et consulter la température

Aucun Handler n'est parfais présentement 5 nov 2018.
Si vous changez de Handler, avec la nouvelle appli, il est obligatoire d'"effacer les données" de l'Appli SmartThings dans les paramètres de votre téléphone.

**Comment by stelpro** [comment]
Bonjour @Danzig69,

Quelle application utilisez-vous? SmartThings Classic ou la nouvelle application (Samsung Connect)? 
Jusqu'à notification contraire, nous vous recommandons d'utiliser l'application "SmartThings Classic".
Nous sommes en train de rendre le tout compatible avec la nouvelle application, mais ce n'est pas encore finalisé.

**Comment by Danzig69** [comment]
La réponse à votre question est à plusieurs endroits dans mon message et je répondais en fonction du sujet donc de la nouvelle application (Samsung Connect) 2018.
Mais au quotidien j'utilise la "vieille" SmartThings Classic car avec Samsung Connect y'a trop de chose qui ne fonctionne pas bien. Trop de perte de fonctionnalité avec Samsung Connect avec TOUS mes objets. 
STZB402+ fonctionne très bien et je les recommandent.

I'm talking about the new one (Samsung Connect) 2018. The one in the subject. My every day usage is with the old one SmartThings Classic.
STZB402+ work very well. I'm satisfied and i recommend them.

**Comment by stelpro** [comment]
Merci de la précision.
En effet, votre message initial mentionnait très clairement la nouvelle application, mais je voulais savoir si vous utilisiez l'application SmartThings Classic également et si vous aviez les mêmes problèmes.

Je suis content que vous appréciez vos thermostats.

Lorsque la compatibilité de nos thermostats sera assurée par SmartThings avec la nouvelle application, il y aura des communications à cet effet.

Bonne journée!

**Comment by bfajg** [comment]
hello Stelpro,

Any news on the new hadler compatible with the latest smartthings APP?

Regards,

**Comment by stelpro** [comment]
Hi Benjamin,

The Stelpro Device Handler is currently in QA, so it's almost there.
However, SmartThings seems to have issue with their new app, it's not quite ready yet.

We are still recommending to use the SmartThings Classic app until further notice.

Best regards

**Comment by bfajg** [comment]
Great, I don’t care much about the app actually. I just need the handler to
work better.

Thx for the quick answer,

Regards,

**Comment by stelpro** [comment]
Hi all,

This is to inform you that the Stelpro Ki Zigbee thermostat is now officially supported by SmartThings.

This means you no longer need to use the device handler code found in github.

The device also works with the new SmartThings app.

There may be still some issues due to the multiple platform changes.
Feel free to report them to SmartThings.

Enjoy!
